[package]
name = "recut"
version = "0.1.0"
authors = ["lyndon <lyndondmackay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
regex = "1.3.9"
pest = "2.1.3"
pest_derive = "2.1.0"